version: "3.8"
services:
  nginx:
    image: veki301/outlook-client
    stdin_open: true
    depends_on:
      - api
    restart: always
    links:
      - api:api
    container_name: client
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 80:80
  api:
    image: veki301/outlook-api
    build:
      dockerfile: Dockerfile
      context: ./server
    container_name: api
    ports:
      - 4000:4000
