name: Staging Deployment to Bots Infrastructure

on:
  push:
    branches:
      - staging

env:
  DOCKER_IMAGE: wire-bot/outlook-addin-server
  SERVICE_NAME: outlook-api-app

jobs:
  publish:
    name: Deployment to Bots Infrastructure
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          echo "BRANCH_NAME=$(git branch --show-current)" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{github.event.after}} | head -n 1)" >> $GITHUB_ENV

      - name: Print environment variables
        env:
          GITHUB_CONTEXT: ${{toJson(github)}}
        run: |
          echo -e "BRANCH_NAME = ${BRANCH_NAME}"
          echo -e "COMMIT_MESSAGE = ${COMMIT_MESSAGE}"
          echo -e "GITHUB_CONTEXT = ${GITHUB_CONTEXT}"

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: eu.gcr.io/${{ env.DOCKER_IMAGE }}

      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.GCR_ACCESS_JSON }}

      - name: Build Docker image
        run: |
          docker build -t ${{ steps.docker_meta.outputs.tags }} server

      - name: Build Docker image
        run: |
          docker push ${{ steps.docker_meta.outputs.tags }}
